In [1]:
!pip install -q scikit-learn==1.6.1 joblib pandas numpy

In [2]:
import pandas as pd
import numpy as np
import joblib

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

print("Libraries imported successfully.")

Libraries imported successfully.


In [3]:
iris = load_iris()

X = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

y = pd.Series(
    iris.target,
    name="target"
)

print("Dataset loaded successfully.")
print("Rows:", X.shape[0])
print("Features:", X.shape[1])

display(X.head())

Dataset loaded successfully.
Rows: 150
Features: 4


,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2


In [4]:
print("Feature names:")
for feature in iris.feature_names:
    print("-", feature)

print("\nTarget classes:")
for index, name in enumerate(iris.target_names):
    print(index, "→", name)

Feature names:
- sepal length (cm)
- sepal width (cm)
- petal length (cm)
- petal width (cm)

Target classes:
0 → setosa
1 → versicolor
2 → virginica


In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 120
Testing samples: 30


In [6]:
model = DecisionTreeClassifier(
    criterion="gini",
    max_depth=3,
    random_state=42
)

model.fit(X_train, y_train)

print("Decision Tree trained successfully.")

Decision Tree trained successfully.


In [7]:
y_pred = model.predict(X_test)

accuracy = accuracy_score(
    y_test,
    y_pred
)

print(f"Accuracy: {accuracy:.4f}")
print(f"Accuracy: {accuracy * 100:.2f}%")

Accuracy: 0.9667
Accuracy: 96.67%


In [8]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Confusion Matrix:
[[10  0  0]
 [ 0  9  1]
 [ 0  0 10]]


In [9]:
print("Classification Report:")

print(
    classification_report(
        y_test,
        y_pred,
        target_names=iris.target_names
    )
)

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      0.90      0.95        10
   virginica       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [12]:
model_bundle = {
    "model": model,
    "class_names": iris.target_names.tolist(),
    "feature_names": iris.feature_names
}

print("Model bundle created successfully.")

Model bundle created successfully.
Model bundle created successfully.


In [13]:
MODEL_FILE = "iris_model.joblib"

joblib.dump(
    model_bundle,
    MODEL_FILE
)

print("Saved:", MODEL_FILE)

Saved: iris_model.joblib


In [14]:
loaded_bundle = joblib.load("iris_model.joblib")

loaded_model = loaded_bundle["model"]

loaded_predictions = loaded_model.predict(X_test)

loaded_accuracy = accuracy_score(
    y_test,
    loaded_predictions
)

print(f"Original accuracy: {accuracy * 100:.2f}%")
print(f"Loaded model accuracy: {loaded_accuracy * 100:.2f}%")

assert np.array_equal(
    y_pred,
    loaded_predictions
)

print("Model verification successful.")

Original accuracy: 96.67%
Loaded model accuracy: 96.67%
Model verification successful.


In [15]:
from google.colab import files

files.download(
    "iris_model.joblib"
)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>